; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:DefaultEnv]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
build_flags = -DCORE_DEBUG_LEVEL=3
; Build only main.cpp
src_filter = +<main.cpp> +<*.cpp> -<main_debug.cpp> -<main_microros.cpp>

[env:debug]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
build_flags = -DCORE_DEBUG_LEVEL=3
; Build only main_debug.cpp
src_filter = +<main_debug.cpp> +<*.cpp> -<main.cpp> -<main_microros.cpp>

[env:microros]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
build_flags = -DCORE_DEBUG_LEVEL=3

; micro-ROS configuration (official platformio library)
lib_deps = https://github.com/micro-ROS/micro_ros_platformio
board_microros_distro = humble
board_microros_transport = wifi

; Use huge partition for micro-ROS
board_build.partitions = huge_app.csv

; Build only main_microros.cpp
build_src_filter = +<main_microros.cpp> +<*.cpp> -<main.cpp> -<main_debug.cpp> -<hello_microros.cpp>

[env:hello_microros]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
build_flags = -DCORE_DEBUG_LEVEL=3

; micro-ROS configuration (official platformio library)
lib_deps = https://github.com/micro-ROS/micro_ros_platformio
board_microros_distro = humble
board_microros_transport = wifi

; Use huge partition for micro-ROS
board_build.partitions = huge_app.csv

; Build only hello_microros.cpp
src_filter = +<hello_microros.cpp> +<*.cpp> -<main.cpp> -<main_debug.cpp> -<main_microros.cpp>
